server:
  port: 8080
spring:
  datasource:
    driver-class-name: ${DRIVER_NAME}
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false
  redis:
    host: localhost
    port: 6379
    password:


logging:
  level:
    root: INFO

security:
  jwt:
    secret-key: ${SECRET_KEY}
    access-token:
      expiration: ${ACCESS_TOKEN_EXPIRATION} # 30 min
    refresh-token:
      expiration: ${REFRESH_TOKEN_EXPIRATION} # 7day