spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      idle-timeout: 600000
      connection-timeout: 65000
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: ${DRIVER_NAME}