server:
  tomcat:
    connection-timeout: 60s
  port: 8080
spring:
  datasource:
    driver-class-name: ${DRIVER_NAME}
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  redis:
    host: localhost
    port: 6379
    password:

  ai:
    model:
      chat: anthropic
    openai:
      api-key: ${OPENAI_API_KEY}
    anthropic:
      base-url: ${ANTHROPIC_BASE_URL}
      completions-path: ${ANTHROPIC_COMPLETIONS_PATH}
      api-key: ${ANTHROPIC_API_KEY}
      version: ${ANTHROPIC_VERSION}
      chat:
        options:
          model: ${ANTHROPIC_CHAT_MODEL}
          max-tokens: ${ANTHROPIC_MAX_TOKENS}
          temperature: ${ANTHROPIC_TEMPERATURE}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  cloud-front:
    region: ${AWS_CLOUD_FRONT_REGION}
    asset-distribution-id: ${CLOUD_FRONT_ASSET_ID}
    domain: ${CLOUD_FRONT_DOMAIN}
  s3:
    region: ${AWS_S3_REGION}
    asset-root-directory: ${S3_ASSET_DIRECTORY}
    bucket-name: ${S3_BUCKET_NAME}

logging:
  level:
    root: DEBUG
    #org.springframework.web: DEBUG
    #org.spring-doc: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG

security:
  secret-key: ${SECRET_KEY}
  scheduler:
    user:
      expiration: ${USER_TOKEN_EXPIRATION}
    group:
      expiration: ${GROUP_TOKEN_EXPIRATION}
  jwt:
    access-token:
      expiration: ${ACCESS_TOKEN_EXPIRATION} # 30 min
    refresh-token:
      expiration: ${REFRESH_TOKEN_EXPIRATION} # 7day